package com.doccure.BE.model;

public class DoctorSpecialization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCTOR_SPECIALIZATION.DOCTOR_SPECIALIZATION_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long doctorSpecializationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCTOR_SPECIALIZATION.DOCTOR_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCTOR_SPECIALIZATION.SPECIALIZATION_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long specializationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCTOR_SPECIALIZATION.DOCTOR_SPECIALIZATION_ID
     *
     * @return the value of DOCTOR_SPECIALIZATION.DOCTOR_SPECIALIZATION_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getDoctorSpecializationId() {
        return doctorSpecializationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCTOR_SPECIALIZATION.DOCTOR_SPECIALIZATION_ID
     *
     * @param doctorSpecializationId the value for DOCTOR_SPECIALIZATION.DOCTOR_SPECIALIZATION_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setDoctorSpecializationId(Long doctorSpecializationId) {
        this.doctorSpecializationId = doctorSpecializationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCTOR_SPECIALIZATION.DOCTOR_ID
     *
     * @return the value of DOCTOR_SPECIALIZATION.DOCTOR_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCTOR_SPECIALIZATION.DOCTOR_ID
     *
     * @param doctorId the value for DOCTOR_SPECIALIZATION.DOCTOR_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCTOR_SPECIALIZATION.SPECIALIZATION_ID
     *
     * @return the value of DOCTOR_SPECIALIZATION.SPECIALIZATION_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getSpecializationId() {
        return specializationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCTOR_SPECIALIZATION.SPECIALIZATION_ID
     *
     * @param specializationId the value for DOCTOR_SPECIALIZATION.SPECIALIZATION_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setSpecializationId(Long specializationId) {
        this.specializationId = specializationId;
    }
}