package com.doccure.BE.model;

import java.util.ArrayList;
import java.util.List;

public class DoctorSpecializationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public DoctorSpecializationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDoctorSpecializationIdIsNull() {
            addCriterion("DOCTOR_SPECIALIZATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andDoctorSpecializationIdIsNotNull() {
            addCriterion("DOCTOR_SPECIALIZATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorSpecializationIdEqualTo(Long value) {
            addCriterion("DOCTOR_SPECIALIZATION_ID =", value, "doctorSpecializationId");
            return (Criteria) this;
        }

        public Criteria andDoctorSpecializationIdNotEqualTo(Long value) {
            addCriterion("DOCTOR_SPECIALIZATION_ID <>", value, "doctorSpecializationId");
            return (Criteria) this;
        }

        public Criteria andDoctorSpecializationIdGreaterThan(Long value) {
            addCriterion("DOCTOR_SPECIALIZATION_ID >", value, "doctorSpecializationId");
            return (Criteria) this;
        }

        public Criteria andDoctorSpecializationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DOCTOR_SPECIALIZATION_ID >=", value, "doctorSpecializationId");
            return (Criteria) this;
        }

        public Criteria andDoctorSpecializationIdLessThan(Long value) {
            addCriterion("DOCTOR_SPECIALIZATION_ID <", value, "doctorSpecializationId");
            return (Criteria) this;
        }

        public Criteria andDoctorSpecializationIdLessThanOrEqualTo(Long value) {
            addCriterion("DOCTOR_SPECIALIZATION_ID <=", value, "doctorSpecializationId");
            return (Criteria) this;
        }

        public Criteria andDoctorSpecializationIdIn(List<Long> values) {
            addCriterion("DOCTOR_SPECIALIZATION_ID in", values, "doctorSpecializationId");
            return (Criteria) this;
        }

        public Criteria andDoctorSpecializationIdNotIn(List<Long> values) {
            addCriterion("DOCTOR_SPECIALIZATION_ID not in", values, "doctorSpecializationId");
            return (Criteria) this;
        }

        public Criteria andDoctorSpecializationIdBetween(Long value1, Long value2) {
            addCriterion("DOCTOR_SPECIALIZATION_ID between", value1, value2, "doctorSpecializationId");
            return (Criteria) this;
        }

        public Criteria andDoctorSpecializationIdNotBetween(Long value1, Long value2) {
            addCriterion("DOCTOR_SPECIALIZATION_ID not between", value1, value2, "doctorSpecializationId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNull() {
            addCriterion("DOCTOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNotNull() {
            addCriterion("DOCTOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdEqualTo(Long value) {
            addCriterion("DOCTOR_ID =", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotEqualTo(Long value) {
            addCriterion("DOCTOR_ID <>", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThan(Long value) {
            addCriterion("DOCTOR_ID >", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DOCTOR_ID >=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThan(Long value) {
            addCriterion("DOCTOR_ID <", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThanOrEqualTo(Long value) {
            addCriterion("DOCTOR_ID <=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIn(List<Long> values) {
            addCriterion("DOCTOR_ID in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotIn(List<Long> values) {
            addCriterion("DOCTOR_ID not in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdBetween(Long value1, Long value2) {
            addCriterion("DOCTOR_ID between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotBetween(Long value1, Long value2) {
            addCriterion("DOCTOR_ID not between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdIsNull() {
            addCriterion("SPECIALIZATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdIsNotNull() {
            addCriterion("SPECIALIZATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdEqualTo(Long value) {
            addCriterion("SPECIALIZATION_ID =", value, "specializationId");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdNotEqualTo(Long value) {
            addCriterion("SPECIALIZATION_ID <>", value, "specializationId");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdGreaterThan(Long value) {
            addCriterion("SPECIALIZATION_ID >", value, "specializationId");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SPECIALIZATION_ID >=", value, "specializationId");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdLessThan(Long value) {
            addCriterion("SPECIALIZATION_ID <", value, "specializationId");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdLessThanOrEqualTo(Long value) {
            addCriterion("SPECIALIZATION_ID <=", value, "specializationId");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdIn(List<Long> values) {
            addCriterion("SPECIALIZATION_ID in", values, "specializationId");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdNotIn(List<Long> values) {
            addCriterion("SPECIALIZATION_ID not in", values, "specializationId");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdBetween(Long value1, Long value2) {
            addCriterion("SPECIALIZATION_ID between", value1, value2, "specializationId");
            return (Criteria) this;
        }

        public Criteria andSpecializationIdNotBetween(Long value1, Long value2) {
            addCriterion("SPECIALIZATION_ID not between", value1, value2, "specializationId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 21 08:31:22 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}