package com.doccure.BE.model;

public class Doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCTOR.DOCTOR_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCTOR.FIRST_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCTOR.LAST_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCTOR.EXPERIENCE
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCTOR.HOSPITAL
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private String hospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCTOR.AVATAR
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCTOR.DOCTOR_ID
     *
     * @return the value of DOCTOR.DOCTOR_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCTOR.DOCTOR_ID
     *
     * @param doctorId the value for DOCTOR.DOCTOR_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCTOR.FIRST_NAME
     *
     * @return the value of DOCTOR.FIRST_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCTOR.FIRST_NAME
     *
     * @param firstName the value for DOCTOR.FIRST_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCTOR.LAST_NAME
     *
     * @return the value of DOCTOR.LAST_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCTOR.LAST_NAME
     *
     * @param lastName the value for DOCTOR.LAST_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCTOR.EXPERIENCE
     *
     * @return the value of DOCTOR.EXPERIENCE
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCTOR.EXPERIENCE
     *
     * @param experience the value for DOCTOR.EXPERIENCE
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setExperience(Long experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCTOR.HOSPITAL
     *
     * @return the value of DOCTOR.HOSPITAL
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCTOR.HOSPITAL
     *
     * @param hospital the value for DOCTOR.HOSPITAL
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCTOR.AVATAR
     *
     * @return the value of DOCTOR.AVATAR
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCTOR.AVATAR
     *
     * @param avatar the value for DOCTOR.AVATAR
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }
}