package com.doccure.BE.model;

import java.math.BigDecimal;

public class InvoiceItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_ITEM.ITEM_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_ITEM.ITEM_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_ITEM.QUANTITY
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private BigDecimal quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_ITEM.PRICE
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_ITEM.INVOICE_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long invoiceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_ITEM.ITEM_ID
     *
     * @return the value of INVOICE_ITEM.ITEM_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_ITEM.ITEM_ID
     *
     * @param itemId the value for INVOICE_ITEM.ITEM_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_ITEM.ITEM_NAME
     *
     * @return the value of INVOICE_ITEM.ITEM_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_ITEM.ITEM_NAME
     *
     * @param itemName the value for INVOICE_ITEM.ITEM_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_ITEM.QUANTITY
     *
     * @return the value of INVOICE_ITEM.QUANTITY
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_ITEM.QUANTITY
     *
     * @param quantity the value for INVOICE_ITEM.QUANTITY
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_ITEM.PRICE
     *
     * @return the value of INVOICE_ITEM.PRICE
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_ITEM.PRICE
     *
     * @param price the value for INVOICE_ITEM.PRICE
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_ITEM.INVOICE_ID
     *
     * @return the value of INVOICE_ITEM.INVOICE_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_ITEM.INVOICE_ID
     *
     * @param invoiceId the value for INVOICE_ITEM.INVOICE_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }
}