package com.doccure.BE.model;

import java.util.Date;

public class Invoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.INVOICE_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long invoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.INVOICE_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private String invoiceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.CREATED_AT
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.STATUS
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE.APPOINTMENT_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long appointmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.INVOICE_ID
     *
     * @return the value of INVOICE.INVOICE_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.INVOICE_ID
     *
     * @param invoiceId the value for INVOICE.INVOICE_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.INVOICE_NAME
     *
     * @return the value of INVOICE.INVOICE_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public String getInvoiceName() {
        return invoiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.INVOICE_NAME
     *
     * @param invoiceName the value for INVOICE.INVOICE_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setInvoiceName(String invoiceName) {
        this.invoiceName = invoiceName == null ? null : invoiceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.CREATED_AT
     *
     * @return the value of INVOICE.CREATED_AT
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.CREATED_AT
     *
     * @param createdAt the value for INVOICE.CREATED_AT
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.STATUS
     *
     * @return the value of INVOICE.STATUS
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.STATUS
     *
     * @param status the value for INVOICE.STATUS
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE.APPOINTMENT_ID
     *
     * @return the value of INVOICE.APPOINTMENT_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getAppointmentId() {
        return appointmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE.APPOINTMENT_ID
     *
     * @param appointmentId the value for INVOICE.APPOINTMENT_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setAppointmentId(Long appointmentId) {
        this.appointmentId = appointmentId;
    }
}