package com.doccure.BE.model;

import java.util.Date;

public class Rating {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RATING.RATING_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long ratingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RATING.COMMENT_RATING
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private String commentRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RATING.RATING
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RATING.CREATED_AT
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RATING.APPOINTMENT_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long appointmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RATING.RATING_ID
     *
     * @return the value of RATING.RATING_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getRatingId() {
        return ratingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RATING.RATING_ID
     *
     * @param ratingId the value for RATING.RATING_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setRatingId(Long ratingId) {
        this.ratingId = ratingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RATING.COMMENT_RATING
     *
     * @return the value of RATING.COMMENT_RATING
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public String getCommentRating() {
        return commentRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RATING.COMMENT_RATING
     *
     * @param commentRating the value for RATING.COMMENT_RATING
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setCommentRating(String commentRating) {
        this.commentRating = commentRating == null ? null : commentRating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RATING.RATING
     *
     * @return the value of RATING.RATING
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RATING.RATING
     *
     * @param rating the value for RATING.RATING
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setRating(Long rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RATING.CREATED_AT
     *
     * @return the value of RATING.CREATED_AT
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RATING.CREATED_AT
     *
     * @param createdAt the value for RATING.CREATED_AT
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RATING.APPOINTMENT_ID
     *
     * @return the value of RATING.APPOINTMENT_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getAppointmentId() {
        return appointmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RATING.APPOINTMENT_ID
     *
     * @param appointmentId the value for RATING.APPOINTMENT_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setAppointmentId(Long appointmentId) {
        this.appointmentId = appointmentId;
    }
}