package com.doccure.BE.model;

import java.math.BigDecimal;
import java.util.Date;

public class Slot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SLOT.SLOT_ID
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    private Long slotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SLOT.START_DATETIME
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    private Date startDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SLOT.END_DATETIME
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    private Date endDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SLOT.DOCTOR_ID
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    private Long doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SLOT.PRICE
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SLOT.SLOT_ID
     *
     * @return the value of SLOT.SLOT_ID
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    public Long getSlotId() {
        return slotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SLOT.SLOT_ID
     *
     * @param slotId the value for SLOT.SLOT_ID
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    public void setSlotId(Long slotId) {
        this.slotId = slotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SLOT.START_DATETIME
     *
     * @return the value of SLOT.START_DATETIME
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    public Date getStartDatetime() {
        return startDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SLOT.START_DATETIME
     *
     * @param startDatetime the value for SLOT.START_DATETIME
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    public void setStartDatetime(Date startDatetime) {
        this.startDatetime = startDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SLOT.END_DATETIME
     *
     * @return the value of SLOT.END_DATETIME
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    public Date getEndDatetime() {
        return endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SLOT.END_DATETIME
     *
     * @param endDatetime the value for SLOT.END_DATETIME
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    public void setEndDatetime(Date endDatetime) {
        this.endDatetime = endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SLOT.DOCTOR_ID
     *
     * @return the value of SLOT.DOCTOR_ID
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SLOT.DOCTOR_ID
     *
     * @param doctorId the value for SLOT.DOCTOR_ID
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SLOT.PRICE
     *
     * @return the value of SLOT.PRICE
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SLOT.PRICE
     *
     * @param price the value for SLOT.PRICE
     *
     * @mbg.generated Fri Oct 25 10:58:19 ICT 2024
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}