package com.doccure.BE.model;

public class Specialization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPECIALIZATION.SPECIALIZATION_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private Long specializationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPECIALIZATION.SPECIALIZATION_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    private String specializationName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPECIALIZATION.SPECIALIZATION_ID
     *
     * @return the value of SPECIALIZATION.SPECIALIZATION_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public Long getSpecializationId() {
        return specializationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPECIALIZATION.SPECIALIZATION_ID
     *
     * @param specializationId the value for SPECIALIZATION.SPECIALIZATION_ID
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setSpecializationId(Long specializationId) {
        this.specializationId = specializationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPECIALIZATION.SPECIALIZATION_NAME
     *
     * @return the value of SPECIALIZATION.SPECIALIZATION_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public String getSpecializationName() {
        return specializationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPECIALIZATION.SPECIALIZATION_NAME
     *
     * @param specializationName the value for SPECIALIZATION.SPECIALIZATION_NAME
     *
     * @mbg.generated Mon Oct 21 08:31:22 ICT 2024
     */
    public void setSpecializationName(String specializationName) {
        this.specializationName = specializationName == null ? null : specializationName.trim();
    }
}