package com.doccure.BE.mapper;

import com.doccure.BE.model.Appointment;
import com.doccure.BE.model.AppointmentExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AppointmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTMENT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    long countByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTMENT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTMENT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByPrimaryKey(Long appointmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTMENT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insert(Appointment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTMENT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insertSelective(Appointment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTMENT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    List<Appointment> selectByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTMENT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    Appointment selectByPrimaryKey(Long appointmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTMENT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Appointment row, @Param("example") AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTMENT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExample(@Param("row") Appointment row, @Param("example") AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTMENT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKeySelective(Appointment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTMENT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKey(Appointment row);
}