package com.doccure.BE.mapper;

import com.doccure.BE.model.Doctor;
import com.doccure.BE.model.DoctorExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    long countByExample(DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByExample(DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByPrimaryKey(Long doctorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insert(Doctor row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insertSelective(Doctor row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    List<Doctor> selectByExample(DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    Doctor selectByPrimaryKey(Long doctorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Doctor row, @Param("example") DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExample(@Param("row") Doctor row, @Param("example") DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKeySelective(Doctor row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKey(Doctor row);
}