package com.doccure.BE.mapper;

import com.doccure.BE.model.DoctorSpecialization;
import com.doccure.BE.model.DoctorSpecializationExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DoctorSpecializationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    long countByExample(DoctorSpecializationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByExample(DoctorSpecializationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByPrimaryKey(Long doctorSpecializationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insert(DoctorSpecialization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insertSelective(DoctorSpecialization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    List<DoctorSpecialization> selectByExample(DoctorSpecializationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    DoctorSpecialization selectByPrimaryKey(Long doctorSpecializationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExampleSelective(@Param("row") DoctorSpecialization row, @Param("example") DoctorSpecializationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExample(@Param("row") DoctorSpecialization row, @Param("example") DoctorSpecializationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKeySelective(DoctorSpecialization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCTOR_SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKey(DoctorSpecialization row);
}