package com.doccure.BE.mapper;

import com.doccure.BE.model.Invoice;
import com.doccure.BE.model.InvoiceExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface InvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    long countByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByPrimaryKey(Long invoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insert(Invoice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insertSelective(Invoice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    List<Invoice> selectByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    Invoice selectByPrimaryKey(Long invoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Invoice row, @Param("example") InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExample(@Param("row") Invoice row, @Param("example") InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKeySelective(Invoice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKey(Invoice row);
}