package com.doccure.BE.mapper;

import com.doccure.BE.model.InvoiceItem;
import com.doccure.BE.model.InvoiceItemExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface InvoiceItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_ITEM
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    long countByExample(InvoiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_ITEM
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByExample(InvoiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_ITEM
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_ITEM
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insert(InvoiceItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_ITEM
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insertSelective(InvoiceItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_ITEM
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    List<InvoiceItem> selectByExample(InvoiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_ITEM
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    InvoiceItem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_ITEM
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExampleSelective(@Param("row") InvoiceItem row, @Param("example") InvoiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_ITEM
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExample(@Param("row") InvoiceItem row, @Param("example") InvoiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_ITEM
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKeySelective(InvoiceItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_ITEM
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKey(InvoiceItem row);
}