package com.doccure.BE.mapper;

import com.doccure.BE.model.Rating;
import com.doccure.BE.model.RatingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RatingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RATING
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    long countByExample(RatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RATING
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByExample(RatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RATING
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByPrimaryKey(Long ratingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RATING
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insert(Rating row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RATING
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insertSelective(Rating row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RATING
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    List<Rating> selectByExample(RatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RATING
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    Rating selectByPrimaryKey(Long ratingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RATING
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Rating row, @Param("example") RatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RATING
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExample(@Param("row") Rating row, @Param("example") RatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RATING
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKeySelective(Rating row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RATING
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKey(Rating row);
}