package com.doccure.BE.mapper;

import com.doccure.BE.model.Slot;
import com.doccure.BE.model.SlotExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SlotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SLOT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    long countByExample(SlotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SLOT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByExample(SlotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SLOT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByPrimaryKey(Long slotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SLOT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insert(Slot row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SLOT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insertSelective(Slot row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SLOT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    List<Slot> selectByExample(SlotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SLOT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    Slot selectByPrimaryKey(Long slotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SLOT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Slot row, @Param("example") SlotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SLOT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExample(@Param("row") Slot row, @Param("example") SlotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SLOT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKeySelective(Slot row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SLOT
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKey(Slot row);
}