package com.doccure.BE.mapper;

import com.doccure.BE.model.Specialization;
import com.doccure.BE.model.SpecializationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecializationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    long countByExample(SpecializationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByExample(SpecializationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByPrimaryKey(Long specializationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insert(Specialization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insertSelective(Specialization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    List<Specialization> selectByExample(SpecializationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    Specialization selectByPrimaryKey(Long specializationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Specialization row, @Param("example") SpecializationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExample(@Param("row") Specialization row, @Param("example") SpecializationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKeySelective(Specialization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIZATION
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKey(Specialization row);
}