package com.doccure.BE.mapper;

import com.doccure.BE.model.Token;
import com.doccure.BE.model.TokenExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    long countByExample(TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByExample(TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int deleteByPrimaryKey(Long tokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insert(Token row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int insertSelective(Token row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    List<Token> selectByExample(TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    Token selectByPrimaryKey(Long tokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Token row, @Param("example") TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByExample(@Param("row") Token row, @Param("example") TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKeySelective(Token row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN
     *
     * @mbg.generated Mon Oct 21 10:51:10 ICT 2024
     */
    int updateByPrimaryKey(Token row);

    List<Token> findAllAccessTokensByUser(Long userId);

    Token findByRefreshToken(String refreshToken);

    Token findByAccessToken(String accessToken);
}