ALTER TABLE TOKEN DISABLE CONSTRAINT FK_TOKEN_USER;
ALTER TABLE DOCTOR_SPECIALIZATION DISABLE CONSTRAINT FK_DOCSPEC_SPEC;
ALTER TABLE DOCTOR_SPECIALIZATION DISABLE CONSTRAINT FK_DOCSPEC_DOCTOR;
ALTER TABLE SLOT DISABLE CONSTRAINT FK_SLOT_DOCTOR;
ALTER TABLE APPOINTMENT DISABLE CONSTRAINT FK_APPOINTMENT_SLOT;
ALTER TABLE APPOINTMENT DISABLE CONSTRAINT FK_APPOINTMENT_DOCSPE;
ALTER TABLE APPOINTMENT DISABLE CONSTRAINT FK_APPOINTMENT_USER;
ALTER TABLE RATING DISABLE CONSTRAINT FK_RATING_APPOINTMENT;
ALTER TABLE INVOICE DISABLE CONSTRAINT FK_INVOICE_APPOINTMENT;
ALTER TABLE INVOICE_ITEM DISABLE CONSTRAINT FK_ITEM_INVOICE;
ALTER TABLE FORGOT_PASS DISABLE CONSTRAINT FK_FPASS_USER;


DELETE FROM INVOICE_ITEM;
DELETE FROM INVOICE;
DELETE FROM RATING;
DELETE FROM APPOINTMENT;
DELETE FROM SLOT;
DELETE FROM DOCTOR_SPECIALIZATION;
DELETE FROM SPECIALIZATION;
DELETE FROM TOKEN;
DELETE FROM FORGOT_PASS;
DELETE FROM DOCTOR;
DELETE FROM USERS;

ALTER TABLE USERS MODIFY(USER_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE TOKEN MODIFY(TOKEN_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE DOCTOR MODIFY(DOCTOR_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE DOCTOR_SPECIALIZATION MODIFY(DOCTOR_SPECIALIZATION_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE SPECIALIZATION MODIFY(SPECIALIZATION_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE SLOT MODIFY(SLOT_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE FORGOT_PASS MODIFY(FP_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE APPOINTMENT MODIFY(APPOINTMENT_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE RATING MODIFY(RATING_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE INVOICE_ITEM MODIFY(ITEM_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE INVOICE MODIFY(INVOICE_ID GENERATED AS IDENTITY (START WITH 1));

ALTER TABLE TOKEN ENABLE CONSTRAINT FK_TOKEN_USER;
ALTER TABLE DOCTOR_SPECIALIZATION ENABLE CONSTRAINT FK_DOCSPEC_SPEC;
ALTER TABLE DOCTOR_SPECIALIZATION ENABLE CONSTRAINT FK_DOCSPEC_DOCTOR;
ALTER TABLE SLOT ENABLE CONSTRAINT FK_SLOT_DOCTOR;
ALTER TABLE APPOINTMENT ENABLE CONSTRAINT FK_APPOINTMENT_SLOT;
ALTER TABLE APPOINTMENT ENABLE CONSTRAINT FK_APPOINTMENT_DOCSPE;
ALTER TABLE APPOINTMENT ENABLE CONSTRAINT FK_APPOINTMENT_USER;
ALTER TABLE RATING ENABLE CONSTRAINT FK_RATING_APPOINTMENT;
ALTER TABLE INVOICE ENABLE CONSTRAINT FK_INVOICE_APPOINTMENT;
ALTER TABLE INVOICE_ITEM ENABLE CONSTRAINT FK_ITEM_INVOICE;
ALTER TABLE FORGOT_PASS ENABLE CONSTRAINT FK_FPASS_USER;


